# Generated by Django 3.2.19 on 2023-06-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='genus',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='plant',
            name='species',
            field=models.CharField(max_length=150),
        ),
    ]
