# Generated by Django 3.2.19 on 2023-06-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20230626_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='sku',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.UniqueConstraint(fields=('common_name',), name='unique_common_name'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.UniqueConstraint(fields=('sku',), name='sku_name'),
        ),
    ]
