# Generated by Django 3.2.19 on 2023-06-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20230627_0747'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plant',
            name='sku_name',
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.UniqueConstraint(fields=('sku',), name='unique_sku_name'),
        ),
    ]
