# Generated by Django 3.2.19 on 2023-07-02 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_user_profile'),
        ('locations', '0003_alter_location_location_plants'),
        ('plants', '0004_auto_20230627_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_state_name', models.CharField(max_length=90, unique=True)),
                ('plant_state_friendly_name', models.CharField(max_length=90)),
                ('next_plant_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_states', to='plants.plantstate')),
            ],
        ),
        migrations.CreateModel(
            name='PlantRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_number', models.IntegerField(blank=True, null=True)),
                ('date_state_changed', models.DateField(auto_now=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_plant_records', to='locations.location')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_plant_records', to='checkout.order')),
                ('plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_records', to='plants.plant')),
                ('plant_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_state_plant_records', to='plants.plantstate')),
            ],
        ),
        migrations.AddConstraint(
            model_name='plantrecord',
            constraint=models.UniqueConstraint(fields=('plant_id',), name='unique_plant_id'),
        ),
    ]
