# Generated by Django 3.2.19 on 2023-07-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_auto_20230702_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantrecord',
            name='plant_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
