# Generated by Django 3.2.19 on 2023-07-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_alter_plantrecord_plant_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
