# Generated by Django 3.2.19 on 2023-07-10 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_plant_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='image_url',
        ),
    ]
