# Generated by Django 3.2.19 on 2023-06-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0004_auto_20230627_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=150)),
                ('location_friendly_name', models.CharField(max_length=150)),
                ('location_plants', models.ManyToManyField(related_name='location_plants', to='plants.Plant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('location_name',), name='unique_location_name'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('location_friendly_name',), name='unique_location_friendly_name'),
        ),
    ]
