# Generated by Django 3.2.19 on 2023-06-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_auto_20230627_1458'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_plants',
            field=models.ManyToManyField(blank=True, related_name='location_plants', to='plants.Plant'),
        ),
    ]
