# Generated by Django 3.2.19 on 2023-06-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_auto_20230627_1458'),
        ('locations', '0002_alter_location_location_plants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_plants',
            field=models.ManyToManyField(related_name='location_plants', to='plants.Plant'),
        ),
    ]
